# Generated by Django 4.1.3 on 2022-11-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
